name: Upload website

on:
  push:
    branches:
      - typescript

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build with Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
      - name: Install Dependencies
        run: npm install
      - name: Create .env with Github Secrets and run script
        run: |
          touch .env
          echo REACT_APP_API_URL=$REACT_APP_API_URL >> .env
          cat .env
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
      - name: Build
        run: npm run build
      - name: Sync with S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'
          SOURCE_DIR: 'build'
